<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\BetterExperience\Patches\ReplaceTexture\ReplacementResourceIO.cs" Link="Shared\ReplacementResourceIO.cs" />
        <Compile Include="..\BetterExperience\Patches\ReplaceTexture\ReplacementResourceKeys.cs" Link="Shared\ReplacementResourceKeys.cs" />
        <Compile Include="..\BetterExperience\Patches\ReplaceTexture\ReplacementResourcePaths.cs" Link="Shared\ReplacementResourcePaths.cs" />
        <InternalsVisibleTo Include="BetterExperience.Test" />
    </ItemGroup>
</Project>
