<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <AssemblyName>Wardrobe.QA</AssemblyName>
    <RootNamespace>Wardrobe.QA</RootNamespace>
    <OutputPath>bin\Debug\</OutputPath>
    <LangVersion>latest</LangVersion>
    <GameDir Condition="'$(GameDir)' == ''">D:\mine\B\programme\AliceInCradle\ver030d</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Plugin.cs" />
    <Compile Include="Isolated.cs" />
    <Compile Include="Effects.cs" />
    <Compile Include="../../../BetterExperience/Patches/ReplaceTexture/PortraitJson.cs"><Link>Shared/PortraitJson.cs</Link></Compile>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="BepInEx"><HintPath>../../../ReferenceLibrary/BepInEx.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../../../ReferenceLibrary/0Harmony.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>../../../ReferenceLibrary/Assembly-CSharp.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="better"><HintPath>../../../ReferenceLibrary/better.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="pixelliner"><HintPath>../../../ReferenceLibrary/pixelliner.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="unsafeAssem"><HintPath>../../../ReferenceLibrary/unsafeAssem.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="spine-unity"><HintPath>../../../ReferenceLibrary/spine-unity.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>../../../ReferenceLibrary/UnityEngine.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>../../../ReferenceLibrary/UnityEngine.CoreModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>../../../ReferenceLibrary/UnityEngine.ImageConversionModule.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
