<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Wardrobe.Runtime.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <ProjectReference Include="../Runtime/Runtime.csproj" />
    <Reference Include="spine-unity"><HintPath>../../../ReferenceLibrary/spine-unity.dll</HintPath></Reference>
  </ItemGroup>
</Project>
